apiVersion: v1
kind: Namespace
metadata:
  name: draw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: draw
  namespace: draw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draw
  template:
    metadata:
      labels:
        app: draw
    spec:
      containers:
        - name: draw
          image: ghcr.io/meatbyte-studio/draw-server:latest
          ports:
            - containerPort: 4444
          env:
            - name: PORT
              value: "4444"
---
apiVersion: v1
kind: Service
metadata:
  name: draw
  namespace: draw
spec:
  selector:
    app: draw
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: draw
  namespace: draw
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: draw.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: draw
                port:
                  number: 4444
