name: Docker Image CI
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker buildx build --load --file Dockerfile --tag draw-server:${{ github.ref_name }} .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag image:tag
        run: docker tag draw-server:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/draw-server:${{ github.ref_name }}

      - name: Push image:tag
        run: docker push ghcr.io/${{ github.repository_owner }}/draw-server:${{ github.ref_name }}

      - name: Tag Docker image:latest
        run: docker tag draw-server:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/draw-server:latest

      - name: Push image:latest
        run: docker push ghcr.io/${{ github.repository_owner }}/draw-server:latest
